
dataloader:
  type: "voxel_dense_map"
  # voxel_dense_map
  map_size: 960
  xy_scale: 2
  z_scale: 2
  voxel_height: 34 # original voxel height
  filter_height_max: 32
  filter_height_min: 3
  random_rotate: True
  crop_size: 384
  filter_height: True
  i_s_weight: 10

net:
  backbone: "unet"
  c0: 16
  loss: 'l1'
  i_s_weight: 10
  

train:
  epoch_num: 50
  lr: 0.0001
  batch_size: 16